array(
			 		'title' => __('Comment',MWB_RWPR_Domain), 
			 		'type'	=> 'title',
			 		),
			 	array(
			 		'title' => __('Enable Comments Points',MWB_RWPR_Domain),
			 		'type'	=> "checkbox",
			 		'id'	=>	"mwb_wpr_general_comment_enable",
			 		'heading' => __('Sign Up',MWB_RWPR_Domain),
			 		'class'	  => 'input-text',
			 		'pro'	  =>  true,
			 		'desc_tip'=> __('Check this box to enable the Comments Points when comment is approved.', MWB_RWPR_Domain),
			 		'desc'	  => __('Enable Comments Points for Rewards',MWB_RWPR_Domain),
			 		),
			 	array(
			 		'title' => __('Enter Comments Points',MWB_RWPR_Domain),
			 		'type'	=> "number",
			 		'id'	=> "mwb_wpr_general_comment_value",
			 		'custom_attributes'   => array('min'=>'1'),
			 		'pro'	  =>  true,
			 		'class'	  => 'input-text mwb_wpr_new_woo_ver_style_text',
			 		'desc_tip'=> __('The points which the new customer will get after their comments are approved.', MWB_RWPR_Domain),
			 		),
			 	array(
					'type' 	=> 'sectionend',
					),